# Generated by Django 5.2 on 2025-08-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0003_alter_plugin_access_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plugin",
            old_name="location",
            new_name="access_location",
        ),
    ]
