# Generated by Django 5.2 on 2025-08-24 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_dnsconfig_uid'),
        ('department', '0005_alter_department_access_level'),
        ('plugin', '0004_rename_location_plugin_access_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plugin',
            name='either_username_password_or_api_key_required',
        ),
        migrations.AddField(
            model_name='plugin',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='provider',
            field=models.CharField(choices=[('nsdl', 'nsdl'), ('unisen', 'unisen'), ('deepvue', 'deepvue')], max_length=255),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='service',
            field=models.CharField(choices=[('pan_validation', 'pan_validation'), ('pan_eligibility', 'pan_eligibility'), ('aadhaar_verification', 'aadhaar_verification'), ('passport_verification', 'passport_verification'), ('vehicle_rc_verification', 'vehicle_rc_verification'), ('bank_account_verification', 'bank_account_verification'), ('upi_verification', 'upi_verification'), ('gst_verification', 'gst_verification'), ('udyam_verification', 'udyam_verification'), ('cin_verification', 'cin_verification')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='plugin',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('password__isnull', False), ('username__isnull', False)), models.Q(('username__exact', ''), _negated=True), models.Q(('password__exact', ''), _negated=True)), models.Q(models.Q(('api_key__isnull', False)), models.Q(('api_key__exact', ''), _negated=True)), models.Q(('client_id__isnull', False), ('client_secret__isnull', False), models.Q(('client_id__exact', ''), _negated=True), models.Q(('client_secret__exact', ''), _negated=True)), _connector='OR'), name='either_username_password_or_api_key_or_client_credentials', violation_error_message='Either username and password or api_key or client credentials must be provided.'),
        ),
    ]
