# Generated by Django 5.2 on 2025-08-26 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_dnsconfig_uid"),
        ("department", "0005_alter_department_access_level"),
        (
            "plugin",
            "0005_remove_plugin_either_username_password_or_api_key_required_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="plugin",
            constraint=models.UniqueConstraint(
                fields=("provider", "service", "company"),
                name="unique_plugin_per_company",
            ),
        ),
    ]
