# Generated by Django 5.2 on 2025-08-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0006_plugin_unique_plugin_per_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="provider",
            field=models.CharField(
                choices=[
                    ("nsdl", "nsdl"),
                    ("unisen", "unisen"),
                    ("deepvue", "deepvue"),
                    ("cell24x7", "cell24x7"),
                    ("novoup", "novoup"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="plugin",
            name="service",
            field=models.CharField(
                choices=[
                    ("pan_validation", "pan_validation"),
                    ("pan_eligibility", "pan_eligibility"),
                    ("aadhaar_verification", "aadhaar_verification"),
                    ("driving_license_verification", "driving_license_verification"),
                    ("vehicle_rc_verification", "vehicle_rc_verification"),
                    ("mobile_to_vehicle_rc", "mobile_to_vehicle_rc"),
                    ("bank_account_verification", "bank_account_verification"),
                    ("ifsc_lookup", "ifsc_lookup"),
                    ("sms_notification", "sms_notification"),
                    ("policy_extraction", "policy_extraction"),
                ],
                max_length=255,
            ),
        ),
    ]
