# Generated by Django 5.2 on 2025-08-23 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_dnsconfig_uid"),
        ("department", "0005_alter_department_access_level"),
        ("motor_quote", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuoteRequest",
            new_name="MotorQuoteRequest",
        ),
    ]
