# Generated by Django 5.2 on 2025-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_quote", "0002_rename_quoterequest_motorquoterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorquoterequest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="motorquoterequest",
            name="name",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
