# Generated by Django 5.1.6 on 2025-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_quote", "0003_motorquoterequest_description_motorquoterequest_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorquoterequest",
            name="source",
            field=models.CharField(
                choices=[("upload", "Upload")], default="upload", max_length=100
            ),
            preserve_default=False,
        ),
    ]
