# Generated by Django 5.2 on 2025-09-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_alter_company_logo_alter_company_url"),
        ("motor_quote", "0005_motorquoterequest_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorquoterequest",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_%(class)s",
                to="company.company",
            ),
        ),
    ]
