# Generated by Django 5.2 on 2025-08-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_policy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorpolicy",
            name="insurer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UIIC", "UIIC"),
                    ("NIC", "NIC"),
                    ("TNI", "TNI"),
                    ("OR", "OR"),
                    ("SBI", "SBI"),
                    ("HDFC", "HDFC"),
                    ("ICICI", "ICICI"),
                    ("BAJAJ", "BAJAJ"),
                    ("RGCL", "RGCL"),
                    ("TATA", "TATA"),
                    ("KTKM", "KTKM"),
                    ("ZURICHKOTAK", "ZURICHKOTAK"),
                    ("IFFCO", "IFFCO"),
                    ("ROYAL", "ROYAL"),
                    ("CHOLA", "CHOLA"),
                    ("MAGMA", "MAGMA"),
                    ("LIB", "LIB"),
                    ("USGI", "USGI"),
                    ("GO", "GO"),
                    ("SHRIRAM", "SHRIRAM"),
                    ("ACKO", "ACKO"),
                    ("NAVI", "NAVI"),
                    ("ZUNO", "ZUNO"),
                    ("RAHEJAQBE", "RAHEJAQBE"),
                    ("KSHEMA", "KSHEMA"),
                    ("FUTURE", "FUTURE"),
                    ("GENERALI_CENTRAL", "GENERALI_CENTRAL"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorpolicy",
            name="policy_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1+1", "PACKAGE_1_1"),
                    ("1+3", "PACKAGE_1_3"),
                    ("1+5", "PACKAGE_1_5"),
                    ("3+3", "PACKAGE_3_3"),
                    ("5+5", "PACKAGE_5_5"),
                    ("1+0", "SAOD_1"),
                    ("2+0", "SAOD_2"),
                    ("3+0", "SAOD_3"),
                    ("0+1", "SATP_1"),
                    ("0+3", "SATP_3"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorpolicy",
            name="policy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Package", "PACKAGE"),
                    ("OD", "OD"),
                    ("TP", "TP"),
                    ("Bundled", "BUNDLED"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorpolicy",
            name="product",
            field=models.CharField(
                blank=True,
                choices=[("Motor", "MOTOR"), ("Health", "HEALTH")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorpolicy",
            name="product_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2W", "DUO"),
                    ("3W", "TRI"),
                    ("4W", "QUAD"),
                    ("6W", "HEX"),
                    ("8W", "OCTA"),
                    ("10W", "DEC"),
                    ("12W", "DUODEC"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorpolicy",
            name="product_sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GCV", "GCV"),
                    ("PCV", "PCV"),
                    ("TW", "TW"),
                    ("PC", "PC"),
                    ("MISC", "MISC"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorpolicy",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[("Private", "PRIVATE"), ("Commercial", "COMMERCIAL")],
                max_length=50,
                null=True,
            ),
        ),
    ]
