# Generated by Django 5.2 on 2025-08-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "motor_policy",
            "0002_motorpolicy_insurer_motorpolicy_policy_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="motorpolicy",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
