# Generated by Django 5.2 on 2025-09-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_policy', '0003_motorpolicy_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorpolicy',
            name='product',
            field=models.CharField(blank=True, choices=[('Motor', 'MOTOR'), ('Health', 'HEALTH'), ('Life', 'LIFE'), ('Non-Motor', 'NON_MOTOR'), ('Personal Accident', 'PERSONAL_ACCIDENT'), ('Travel', 'TRAVEL')], max_length=50, null=True),
        ),
    ]
