# Generated by Django 5.2 on 2025-09-05 11:50

import utils.nanoid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_policy', '0006_alter_motorpolicy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorpolicy',
            name='uid',
            field=models.CharField(db_index=True, default=utils.nanoid_utils.default_nanoid, editable=False, max_length=30, unique=True),
        ),
    ]
