# Generated by Django 5.2 on 2025-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motor_policy", "0007_alter_motorpolicy_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorpolicy",
            name="insurer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UIIC", "UIIC"),
                    ("NIC", "NIC"),
                    ("TNI", "TNI"),
                    ("OR", "OR"),
                    ("GIC", "GIC"),
                    ("SBI", "SBI"),
                    ("HDFC", "HDFC"),
                    ("ICICI", "ICICI"),
                    ("BAJAJ", "BAJAJ"),
                    ("RGCL", "RGCL"),
                    ("TATA", "TATA"),
                    ("KTKM", "KTKM"),
                    ("ZURICHKOTAK", "ZURICHKOTAK"),
                    ("IFFCO", "IFFCO"),
                    ("ROYAL", "ROYAL"),
                    ("CHOLA", "CHOLA"),
                    ("MAGMA", "MAGMA"),
                    ("LIB", "LIB"),
                    ("USGI", "USGI"),
                    ("GO", "GO"),
                    ("SHRIRAM", "SHRIRAM"),
                    ("BHARTIAXA", "BHARTIAXA"),
                    ("ACKO", "ACKO"),
                    ("NAVI", "NAVI"),
                    ("ZUNO", "ZUNO"),
                    ("RAHEJAQBE", "RAHEJAQBE"),
                    ("KSHEMA", "KSHEMA"),
                    ("FUTURE", "FUTURE"),
                    ("GENERALI_CENTRAL", "GENERALI_CENTRAL"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
